[package]
name = "numerical_algo_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
macroquad = "0.4.8"
approx = "0.5.0"
rand = "0.8.5"